# Generated by Django 2.1.5 on 2019-03-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='workoutname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
